<a href="https://colab.research.google.com/github/rameshavinash94/Tensor_Operations/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **IMPORTING LIBRARIES**

In [2]:
import tensorflow as tf
import numpy as np
import torch

### **TENSORFLOW**

**BASIC OPERATIONS**

In [13]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(10)
print(rank_0_tensor)

tf.Tensor(10, shape=(), dtype=int32)


In [14]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [15]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [16]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [18]:
#convert to numpy array

np.array(rank_2_tensor)
#or
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [34]:
a=tf.constant([[1,2]])
b=tf.constant([[3,4],[4,5]])

#math operations
print(tf.add(a,b),"\n")
print(tf.multiply(a,b),"\n")
print(tf.matmul(a,b))

tf.Tensor(
[[4 6]
 [5 7]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  8]
 [ 4 10]], shape=(2, 2), dtype=int32) 

tf.Tensor([[11 14]], shape=(1, 2), dtype=int32)


In [36]:
#the above operations via operators

print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[4 6]
 [5 7]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  8]
 [ 4 10]], shape=(2, 2), dtype=int32) 

tf.Tensor([[11 14]], shape=(1, 2), dtype=int32) 



In [106]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


**SHAPES**

Tensors have shapes.

Shape: The length (number of elements) of each of the axes of a tensor.

Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

Axis or Dimension: A particular dimension of a tensor.

Size: The total number of items in the tensor, the product shape vector.

In [46]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [48]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


**INDEXING**

In [49]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [50]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())
print("second from last:", rank_1_tensor[-2].numpy())

First: 0
Second: 1
Last: 34
second from last: 21


In [51]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [66]:
rank_2_tensor=tf.random.normal([3,3])

In [67]:
rank_2_tensor.numpy()

array([[-0.49820128,  1.4629396 ,  0.37782827],
       [ 0.91511905,  0.46339315, -0.18891314],
       [ 1.3656927 ,  1.0819421 , -0.5308466 ]], dtype=float32)

In [68]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

0.46339315


In [69]:
# Get row and column tensors
print("third row:", rank_2_tensor[2, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("second item in last column:", rank_2_tensor[1, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")
print("Skip the last row:")
print(rank_2_tensor[:-1, :].numpy(), "\n")

third row: [ 1.3656927  1.0819421 -0.5308466]
Second column: [1.4629396  0.46339315 1.0819421 ]
Last row: [ 1.3656927  1.0819421 -0.5308466]
second item in last column: -0.18891314
Skip the first row:
[[ 0.91511905  0.46339315 -0.18891314]
 [ 1.3656927   1.0819421  -0.5308466 ]] 

Skip the last row:
[[-0.49820128  1.4629396   0.37782827]
 [ 0.91511905  0.46339315 -0.18891314]] 



**Manipulating Shapes**

In [71]:
x = tf.random.normal([3,1])
print(x.shape)

(3, 1)


In [72]:
# You can convert this object into a Python list, too
print(x.shape.as_list())

[3, 1]


In [74]:
#reshape tensor
reshape = tf.reshape(x, [1, 3])
print(reshape.shape)

(1, 3)


In [75]:
# A `-1` passed in the `shape` argument says "Whatever fits".
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [76]:
#Typically the only reasonable use of tf.reshape is to combine or split adjacent axes (or add/remove 1s).

print(tf.reshape(rank_3_tensor, [3*5, 2]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]], shape=(15, 2), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


**DTYPES**

*If we don't specify the dtype, TensorFlow chooses a datatype that can represent your data. TensorFlow converts Python integers to tf.int32 and Python floating point numbers to tf.float32. Otherwise TensorFlow uses the same rules NumPy uses when converting to arrays.*

In [77]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


**BRADCASTING**

Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

In [78]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [79]:
# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [80]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # Again, operator overloading

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [81]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


**Ragged Tensors**

A tensor with variable numbers of elements along some axis is called "ragged". Use tf.ragged.RaggedTensor for ragged data.

For example, This cannot be represented as a regular tensor:

In [82]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [83]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [84]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [85]:
print(ragged_tensor.shape)

(4, None)


**String tensors**

In [86]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [87]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [88]:
#tf.string.to_number

text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


you can't use tf.cast to turn a string tensor into numbers, you can convert it into bytes, and then into numbers.

In [89]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [90]:
# Or split it up as unicode and then decode it
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


**Sparse Tensors**

In [91]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


### **PYTORCH**

**BASIC OPERATIONS**

In [10]:
rank_0_tensor = torch.tensor(10)
print(rank_0_tensor)
print(rank_0_tensor.dtype)
#default dtype
torch.get_default_dtype()

tensor(10)
torch.int64


torch.float32

In [92]:
# Let's make this a float tensor.
rank_1_tensor = torch.tensor([2.0, 3.0, 4.0])
print(rank_1_tensor)

tensor([2., 3., 4.])


In [93]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = torch.tensor([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=torch.float16)
print(rank_2_tensor)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16)


In [94]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = torch.tensor([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])


In [95]:
#convert to numpy array

np.array(rank_2_tensor)
#or
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [96]:
a=torch.tensor([[1,2]])
b=torch.tensor([[3,4],[4,5]])

#math operations
print(torch.add(a,b),"\n")
print(torch.multiply(a,b),"\n")
print(torch.matmul(a,b))

tensor([[4, 6],
        [5, 7]]) 

tensor([[ 3,  8],
        [ 4, 10]]) 

tensor([[11, 14]])


In [97]:
#the above operations via operators

print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tensor([[4, 6],
        [5, 7]]) 

tensor([[ 3,  8],
        [ 4, 10]]) 

tensor([[11, 14]]) 



In [105]:
from torch import nn

c = torch.tensor([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(torch.max(c))
# Find the index of the largest value
print(torch.argmax(c))
# Compute the softmax
m = nn.Softmax(dim=1)
print(m(c))

tensor(10.)
tensor(2)
tensor([[2.6894e-01, 7.3106e-01],
        [9.9988e-01, 1.2339e-04]])


**SHAPES**

Tensors have shapes.

Shape: The length (number of elements) of each of the axes of a tensor.

Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

Axis or Dimension: A particular dimension of a tensor.

Size: The total number of items in the tensor, the product shape vector.

In [107]:
rank_4_tensor = torch.zeros([3, 2, 4, 5])

In [108]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: torch.float32
Number of axes: 4
Shape of tensor: torch.Size([3, 2, 4, 5])
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


**INDEXING**

In [109]:
rank_1_tensor = torch.tensor([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [110]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())
print("second from last:", rank_1_tensor[-2].numpy())

First: 0
Second: 1
Last: 34
second from last: 21


In [115]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", torch.flip(rank_1_tensor,[0,]).numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [117]:
rank_2_tensor=torch.rand([3,3])

In [118]:
rank_2_tensor.numpy()

array([[0.8046879 , 0.3725556 , 0.05664635],
       [0.29128015, 0.8679979 , 0.02157706],
       [0.41456252, 0.83407855, 0.8261317 ]], dtype=float32)

In [119]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

0.8679979


In [120]:
# Get row and column tensors
print("third row:", rank_2_tensor[2, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("second item in last column:", rank_2_tensor[1, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")
print("Skip the last row:")
print(rank_2_tensor[:-1, :].numpy(), "\n")

third row: [0.41456252 0.83407855 0.8261317 ]
Second column: [0.3725556  0.8679979  0.83407855]
Last row: [0.41456252 0.83407855 0.8261317 ]
second item in last column: 0.02157706
Skip the first row:
[[0.29128015 0.8679979  0.02157706]
 [0.41456252 0.83407855 0.8261317 ]] 

Skip the last row:
[[0.8046879  0.3725556  0.05664635]
 [0.29128015 0.8679979  0.02157706]] 



**Manipulating Shapes**

In [121]:
x = torch.rand([3,1])
print(x.shape)

torch.Size([3, 1])


In [123]:
# You can convert this object into a Python list, too
print(list(x.shape))

[3, 1]


In [124]:
#reshape tensor
reshape = torch.reshape(x, [1, 3])
print(reshape.shape)

torch.Size([1, 3])


In [125]:
# A `-1` passed in the `shape` argument says "Whatever fits".
print(torch.reshape(rank_3_tensor, [-1]))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])


In [126]:
#Typically the only reasonable use of tf.reshape is to combine or split adjacent axes (or add/remove 1s).

print(torch.reshape(rank_3_tensor, [3*5, 2]), "\n")
print(torch.reshape(rank_3_tensor, [3, -1]))

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]) 

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])


**DTYPES**

*If we don't specify the dtype, pytorch chooses a datatype that can represent your data.

In [142]:
the_f64_tensor = torch.tensor([2.2, 3.3, 4.4], dtype=torch.float64)
the_f16_tensor = the_f64_tensor.type(torch.half)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = the_f16_tensor.type(torch.uint8)
print(the_u8_tensor)

tensor([2, 3, 4], dtype=torch.uint8)


**BRADCASTING**

Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

In [143]:
x = torch.tensor([1, 2, 3])

y = torch.tensor(2)
z = torch.tensor([2, 2, 2])
# All of these are the same computation
print(torch.multiply(x, 2))
print(x * y)
print(x * z)

tensor([2, 4, 6])
tensor([2, 4, 6])
tensor([2, 4, 6])


In [146]:
# These are the same computations
x = torch.reshape(x,[3,1])
y = torch.arange(1, 5)
print(x, "\n")
print(y, "\n")
print(torch.multiply(x, y))

tensor([[1],
        [2],
        [3]]) 

tensor([1, 2, 3, 4]) 

tensor([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12]])


In [147]:
x_stretch = torch.tensor([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = torch.tensor([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # Again, operator overloading

tensor([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12]])


In [148]:
print(torch.broadcast_to(torch.tensor([1, 2, 3]), [3, 3]))

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


**Sparse Tensors**

In [157]:
i = [[0, 1, 1],
         [2, 0, 2]]
v =  [[3, 4], [5, 6], [7, 8]]
s = torch.sparse_coo_tensor(i, v, (2, 3, 2))
s

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([[3, 4],
                      [5, 6],
                      [7, 8]]),
       size=(2, 3, 2), nnz=3, layout=torch.sparse_coo)

In [158]:
s.to_dense()

tensor([[[0, 0],
         [0, 0],
         [3, 4]],

        [[5, 6],
         [0, 0],
         [7, 8]]])

### **EINSUM OPERATIONS**

**Useful Format Strings**


Vector inner product: "a,a->" (Assumes two vectors of same length)

Vector element-wise product: "a,a->a" (Assumes two vectors of same length)

Vector outer product: "a,b->ab" (Vectors not necessarily same length.)

Matrix transposition: "ab->ba"

Matrix diagonal: "ii->i"

Matrix trace: "ii->"

1-D Sum: "a->"

2-D Sum: "ab->"

3-D Sum: "abc->"

Matrix inner product "ab,ab->" (If you pass twice the same argument, it becomes a matrix L2 norm)

Left-multiplication Matrix-Vector: "ab,b->a"

Right-multiplication Vector-Matrix: "a,ab->b"

Matrix Multiply: "ab,bc->ac"

Batch Matrix Multiply: "Yab,Ybc->Yac"

Quadratic form / Mahalanobis Distance: "a,ab,b->"

In [159]:
#MATRIX TRANSPOSE
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->ji', [a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [160]:
#SUM
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->', [a])

tensor(15)

In [161]:
#COLUMN SUM

a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->j', [a])

tensor([3, 5, 7])

In [162]:
#ROW SUM

a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->i', [a])

tensor([ 3, 12])

In [163]:
#MATRIX-VECTOR MULTIPLICATION

a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)
torch.einsum('ik,k->i', [a, b])

tensor([ 5, 14])

In [164]:
# MATRIX-MATRIX MULTIPLICATION

a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
torch.einsum('ik,kj->ij', [a, b])

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [167]:
#DOT PRODUCT

a = torch.arange(3)
b = torch.arange(3,6)  # -- a vector of length 3 containing [3, 4, 5]
print(torch.einsum('i,i->', [a, b]))

a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
print(torch.einsum('ij,ij->', [a, b]))

tensor(14)
tensor(145)


In [168]:
# HADAMARD PRODUCT

a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
torch.einsum('ij,ij->ij', [a, b])

tensor([[ 0,  7, 16],
        [27, 40, 55]])

In [169]:
# OUTER PRODUCT

a = torch.arange(3)
b = torch.arange(3,7)  # -- a vector of length 4 containing [3, 4, 5, 6]
torch.einsum('i,j->ij', [a, b])

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

In [170]:
#BATCH MATRIX MULTIPLICATION

a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
torch.einsum('ijk,ikl->ijl', [a, b])

tensor([[[ 2.4661,  0.7348,  2.2051],
         [-1.8173, -2.6815,  1.3218]],

        [[ 0.0780,  1.7867, -1.4621],
         [ 2.0603,  0.3866, -1.1232]],

        [[ 4.0987,  1.9768, -5.2628],
         [ 2.1673, -0.1674, -4.6203]]])

In [171]:
# TENSOR CONTRACTION

a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
torch.einsum('pqrs,tuqvr->pstuv', [a, b]).shape

torch.Size([2, 7, 11, 13, 17])

In [172]:
#BILINEAR TRANSFORMATION

a = torch.randn(2,3)
b = torch.randn(5,3,7)
c = torch.randn(2,7)
torch.einsum('ik,jkl,il->ij', [a, b, c])

tensor([[-0.1843, -0.8465,  0.7033,  0.8509,  0.7929],
        [ 1.7082, -1.8920,  1.6673,  4.0111, -1.5874]])